# Generated by Django 5.2.6 on 2025-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='inventory',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
